// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvm06PyKBvTCrfJoodCpHfOsxuazeVLCQ',
    appId: '1:1032934995788:web:8ef832ef127fc0d90ec1e9',
    messagingSenderId: '1032934995788',
    projectId: 'chatapp-5ae9a',
    authDomain: 'chatapp-5ae9a.firebaseapp.com',
    storageBucket: 'chatapp-5ae9a.appspot.com',
    measurementId: 'G-P5MDN5LLTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGjYuluIl1q7JrqW9qzISQo-XodZlogxA',
    appId: '1:1032934995788:android:fbd7711d259af3fd0ec1e9',
    messagingSenderId: '1032934995788',
    projectId: 'chatapp-5ae9a',
    storageBucket: 'chatapp-5ae9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Vd1jcbada1Wf8ASf0uyv7OKU357ke3c',
    appId: '1:1032934995788:ios:36b4ffdc96921f600ec1e9',
    messagingSenderId: '1032934995788',
    projectId: 'chatapp-5ae9a',
    storageBucket: 'chatapp-5ae9a.appspot.com',
    iosClientId: '1032934995788-luagunrslsu4sl2b29919d3mi43v9ucp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLesson12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvm06PyKBvTCrfJoodCpHfOsxuazeVLCQ',
    appId: '1:1032934995788:web:48c4a1525843e8760ec1e9',
    messagingSenderId: '1032934995788',
    projectId: 'chatapp-5ae9a',
    authDomain: 'chatapp-5ae9a.firebaseapp.com',
    storageBucket: 'chatapp-5ae9a.appspot.com',
    measurementId: 'G-S5JSMTNBSD',
  );
}
